# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' LossD
#'
#' \loadmathjax This function evaluates the following quadratic loss function
#' \mjsdeqn{L(\beta) = (X\beta - Y)^2}
#' @param b [vector] the vector of \mjseqn{\beta} parameters in the formula above.
#' @param X [matrix] the design matrix \code{X} in the formula above.
#' @param Y [vector] the response vector \code{Y} in the formula above.
#' 
#' @return [double] the function evaluation
#' @export
LossD <- function(b, X, Y) {
    .Call(`_DescendMethods_LossD`, b, X, Y)
}

#' @export
try_rcpp <- function(x) {
    .Call(`_DescendMethods_try_rcpp`, x)
}

