# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Proto_in_cplusplus
#'
#' @export
Proto_in_cplusplus <- function() {
    .Call(`_DescendMethods_Proto_in_cplusplus`)
}

#' @export
try_rcpp <- function(x) {
    .Call(`_DescendMethods_try_rcpp`, x)
}

