# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
LossD <- function(b, X, Y) {
    .Call(`_DescendMethods_LossD`, b, X, Y)
}

#' @export
try_rcpp <- function(x) {
    .Call(`_DescendMethods_try_rcpp`, x)
}

